lsst-uk/lsst-adler

src/adler/dataclasses/AdlerPlanetoid.py
src/adler/dataclasses/DataSchema.py

Fixes #39.
I have refactored the data-classes a bit. I did not make as many changes as anticipated - I have mostly just moved work out of __init__ and consolidated the get_from_table methods into a single method. It's more testable now.
I have also added docstrings in the numpydoc format.

Small data-class refactor.

---

src/adler/dataclasses/AdlerPlanetoid.py
src/adler/dataclasses/DataSchema.py

Fixes #54.
- All DataSchema child classes are now Python dataclasses, with their attributes initialised with empty defaults.
- Docstrings have been updated explaining each attribute. I pulled the descriptions directly from https://dm.lsst.org/sdm_schemas/browser/dp03.html.
Fixes #55.
- I am no longer storing the SQL query and the AstroPy data table on the DataSchema objects. Because that would be silly.
Additional changes:
- I made a tiny change so that `mjd` is instead being stored as `midpointMjdTai` to bring it in line with the DiaSource table column heading.
- Corrected some docstrings.

Data classes

---

docs/requirements.txt
pyproject.toml

added matplotlib to the requirements to enable plotting with the demo notebooks
Fixes #61

add matplotlib requirement

---

src/adler/dataclasses/AdlerData.py
src/adler/dataclasses/AdlerPlanetoid.py
src/adler/dataclasses/DataSchema.py
tests/adler/dataclasses/dummy_test.py
tests/adler/dataclasses/test_AdlerData.py

Fixes #53.
- Created the AdlerData class, which will store all calculated AdlerData values.
- AdlerPlanetoid now creates an instance of the AdlerData class as a class attribute on initialisation
- Wrote a method, `AdlerData.populate_phase_parameters()`, which should allow for easy population.
- Wrote a unit test.
Fixes #68.
- Changed instances of `sys.exit()` to `raise Exception()` instead.
Fixes #67:
- num_obs has been added to the Observations object.
Fixes #63.
- Fixed a typo.
Fixes #64.
- Removed unnecessary `.to_table()` call.

Initial commit of AdlerData class.

---

.gitignore
src/adler/dataclasses/AdlerData.py
tests/adler/dataclasses/test_AdlerData.py

Fixes #70.
- `AdlerData.print_data()` will clearly print out the data stored in AdlerData.
- Wrote a unit test for this method.
Fixes #74.
- `AdlerData.get_phase_parameters_in_filter()` returns a dictionary of the phase parameters in a specified filter and model. Chose a dictionary for clarity here.
- Wrote a unit test for this method.
Fixes #72.
- The unpopulated class attributes on AdlerData now fill with nans on initialisation, to make it clear there is no real data in them yet. The exception is nobs_adler, which is an array of ints and therefore initialises with zeros.
Fixes #73.
- The user can now use AdlerData.populate_phase_parameters() to update only select parameters. If not updating the full set, simply specify the arguments and (if necessary) the model in the function call. 
- …

Fixes/methods on AdlerData.

---

src/adler/adler.py
src/adler/dataclasses/AdlerPlanetoid.py

Fixes #36.
- You can now specify a date range, either on the command line or when creating an AdlerPlanetoid object in a Jupyter notebook.
- This is done on the command line with the `-d --date_range` argument (where you simply follow the flag with two numbers) or on AdlerPlanetoid by passing `date_range=[<min_date>, <max_date>]` to `construct_from_RSP()`.
- Dates should be in MJD(TAI).

Adding dates functionality.

---

src/adler/dataclasses/AdlerData.py
src/adler/dataclasses/AdlerPlanetoid.py
tests/adler/dataclasses/test_AdlerData.py

Refactor ahead of #69.
Essentially, while working on the above issue, I realised that AdlerData in its current state was too confusing on the developer end and I was struggling to work with it. The user-end is mostly unchanged apart from some exceptions listed below.
Changes on the developer end:
- AdlerData now stores a list of FilterDependentAdler objects to store filter-dependent values. These in turn store lists of PhaseModelDependentAdler objects to store the phase model-dependent values. This replaces the nested lists and is much more consistent with the behaviour of the rest of the code. This is also more scaleable: new dataclasses can be created and attached similarly as Adler calculates more values. Also, it doesn't break my brain.
- The names of the various filter-dependent and …

AdlerData refactor.

---

src/adler/adler.py
src/adler/dataclasses/MPCORB.py
src/adler/dataclasses/Observations.py
src/adler/dataclasses/SSObject.py
src/adler/dataclasses/dataclass_utilities.py
src/adler/utilities/AdlerCLIArguments.py
tests/adler/dataclasses/test_AdlerPlanetoid.py
tests/adler/dataclasses/test_MPCORB.py
tests/adler/dataclasses/test_Observations.py
tests/adler/dataclasses/test_dataclass_utilities.py
tests/adler/utilities/test_AdlerCLIArguments.py

Fixes #85.
- Wrote a class, AdlerCLIArguments, which takes the argparse.Namespace object as input and stores and validates all of the command-line arguments.
- Currently it performs some basic checks to make sure the command-line input is sensible. This can easily be added to as we invent more command-line arguments or come up with more interesting ways the user can provide silly input.
- Wrote unit test and docstrings for the class.
- Rewrote adler.py to fit in with the new code.
Fixes #34.
- If the RSP has not populated a particular field in the table (for example, DP0.3 doesn't have any values for the u or y filter in DIASource/SSSource), we now check for this, populate that dataclass attribute with a NaN, and print a warning to the terminal. 
- The original warning has been suppressed …

Error handling and CLI argument validation

---

src/adler/dataclasses/AdlerPlanetoid.py
tests/adler/dataclasses/test_AdlerPlanetoid.py

Fixes #86.
- If the user supplies information which returns an empty table from the RSP or the SQL database (for example, the SSObjectID is wrong or illegitimate, or there simply aren't any observations in the filter(s) the user chose), then the code gracefully fails with an informative error message.
- Wrote unit tests to ensure this behaviour.
Fixes #88.
- If any of the SQL queries on the RSP or a SQL database return an empty table, the code no longer fails quietly and instead errors out gracefully with an informative error message.
- Wrote unit tests to ensure this behaviour.
Fixes #116.
- If there are no observations for the object in the user's requested filters, the code prints a warning and then eliminates that filter from the list, so no information for that filter will be …

Error handling 

---

src/adler/adler.py
src/adler/dataclasses/AdlerData.py
src/adler/dataclasses/AdlerPlanetoid.py
src/adler/dataclasses/dataclass_utilities.py
src/adler/utilities/AdlerCLIArguments.py
src/adler/utilities/adler_logging.py
tests/adler/utilities/test_AdlerCLIArguments.py
tests/adler/utilities/test_adler_logging.py

Fixes #109.
- Added command-line arguments to let the user specify an output path and the database name to write to. We will need this anyway, and I also need a place to save the logs.
- Wrote a unit test to cover the new arguments.
- Wrote a function to set up logging for Adler.
- Added log set-up to dataclasses.
- Ensured current warnings/errors are written to the log.
- Added informative logging messages.
- Added a unit test for the setup function.

Adding output CL arguments, setting up logging.

---

notebooks/plotting_utilities.ipynb
src/adler/utilities/plotting_utilities.py

Fixes #112.
This is a start at adding some plotting utility functions, e.g. making phase curve plots from adler objects. I have tried to write this such that a matplotlib figure object is returned by the function, this can either be displayed or manipulated further.

phase curve plot func

---

notebooks/outlier_detection.ipynb
src/adler/utilities/science_utilities.py
tests/adler/utilities/test_science_utilities.py

Fixes #106
I have added some simple and generic utility functions to detect outliers (e.g. outlying photometric wrt a phase curve model). I need to refine the example notebook and add unit tests.

106 outlying photometry checker

---

docs/conf.py
pyproject.toml

Fixes #59.
- Changes the name of the project in pyproject.toml to "lsst-adler" to avoid conflict with an existing PyPi package.
- Once installed, the actual modules are still accessed in the same way, i.e. from `adler.dataclasses.AdlerPlanetoid import AdlerPlanetoid` still works, and the adler call on the command line works in the same way. The only thing that is different is the package name. 
- I tested this in a fresh Conda environment with a fresh pip install and it's happy enough but I would VERY MUCH like someone else to double-check.

59 renaming project

---

.gitignore

Fixes #124.
- Added .err and .png to the .gitignore

124 adding .err and .png to gitignore

---

src/adler/utilities/AdlerCLIArguments.py
tests/adler/utilities/test_AdlerCLIArguments.py

Fixes #136 .
- Added validation for the `--sql_filename` command-line argument that makes sure the filename exists.
- Fixed a unit test that did not do what I thought it did.
- Wrote a unit test to cover this.

136 Validating and testing new argument

---

src/adler/dataclasses/AdlerPlanetoid.py
src/adler/dataclasses/MPCORB.py
src/adler/dataclasses/Observations.py
src/adler/dataclasses/SSObject.py
src/adler/dataclasses/dataclass_utilities.py

Fixes #143.
- There is now a constructor, `AdlerPlanetoid.construct_from_JSON()`, which allows you to construct the AdlerPlanetoid object from a JSON file. This is so we can create the object from a Kafka alert.
- Note that it assumes there is only a single value for each JSON key, i.e. that none of them will be lists.
- Also note that this has not been unit tested.
Describe your changes.

143 Adding JSON constructor methods.

---

src/adler/__init__.py
src/adler/dataclasses/AdlerPlanetoid.py
src/adler/dataclasses/MPCORB.py
src/adler/dataclasses/Observations.py
src/adler/dataclasses/SSObject.py
src/adler/dataclasses/dataclass_utilities.py
src/adler/lasair/cassandra_fetcher.py
src/adler/utilities/AdlerCLIArguments.py

Fixes #151.
- Made a class, `CassandraFetcher()`, which pulls data from the Cassandra DP0.3 database set up by Roy.
- Added a constructor method: `AdlerPlanetoid.construct_from_cassandra()`. Does what you'd expect!
- Eventually I will move this into the lasair-adler repo. For now, however, it can live here.

Adding functionality to grab lightcurves from Cassandra.

---

README.md
docs/index.rst
docs/notebooks.rst
docs/notebooks/colour_functions_example.ipynb
docs/notebooks/outlier_detection_example.ipynb
docs/notebooks/plotting_utilities_example.ipynb

Fixes #168.
Adding additional notebooks to read the docs to cover plotting, outlier detection and colour measurement.

more nbs for docs

---

pyproject.toml
src/adler/objectdata/AdlerData.py
tests/adler/objectdata/test_AdlerData.py
tests/adler/science/test_PhaseCurve.py

Fixes #163.
- AdlerData now correctly overwrites database values. 
- The database/table is set up so that there will only ever be one entry for each ssObjectID: i.e. ssObjectID is the primary key and will be unique.
- On writeout, AdlerData tries to do an INSERT, and if that fails (because the ssObjectID exists), it will instead UPDATE the values in the specified columns.
- Wrote some unit tests to make sure this works as expected.
I also changed the timestamp column to an MJD and cleaned up the comments in the unit test (sorry!) because I couldn't see what I was doing 😅
At some point I may shift the database code out into its own class, especially when it comes to writing to the MariaDB database on the cloud, but that can happen later.

163 database tweaks

---

src/adler/science/PhaseCurve.py
tests/adler/science/test_PhaseCurve.py

Fixes #191
Adding a function that can calculate the absolute minimum and maximum values of reduced magnitude given the uncertainties on the PhaseCurve parameters.

PhaseCurve bounds
